[build]
  command = "make build -j"
  functions = "functions-dist"
  publish = "public"
[build.environment]
  HUGO_VERSION = "0.49"
  GO_IMPORT_PATH = "github.com/comp500/sensor-website2/functions/daily"
[template.environment]
  HUGO_GOOGLEANALYTICS = ""
  HUGO_PARAMS = ""
  HUGO_TITLE = ""
  GCP_PROJECT_ID = ""
  GCP_CREDENTIALS_JSON = ""