[build]
  command = "make build -j"
  functions = "functions-dist"
  publish = "public"
[build.environment]
  HUGO_VERSION = "0.49"
  GO_IMPORT_PATH = "github.com/comp500/sensor-website2/functions/daily"
[template.environment]
  HUGO_GOOGLEANALYTICS = "Your Google Analytics ID, leave blank if unused"
  HUGO_PARAMS = "The JSON parameters for Hugo"
  HUGO_TITLE = "The title of your website"
  GCP_PROJECT_ID = "The GCP project id"
  GCP_CREDENTIALS_JSON = "The GCP service account JSON file, base64 encoded"
  DATA_TIMEZONE = "The IANA timezone that your data is recorded in"